site_name: Scattered Thoughts
theme:
  name: material
docs_dir: docs
nav:
  - Home: index.md
  - Articles:
      - A Little Exploration of LoRAs: articles/a-little-exploration-of-loras.md
      - El círculo encantado: articles/circulo-encantado.md